[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sagittal_average"
version = "1.0.0"
dependencies = ["numpy",
]

[project.scripts]
greet = "sagittal_average.command:process"

[tool.hatch.build.targets.wheel]
packages = [
  "src/sagittal_average",
]
